[tools]
selene = { source = "Roblox/Kampfkarren-selene", version = "=0.29.0" }
stylua = { source = "Roblox/JohnnyMorganz-StyLua", version = "=2.0.1" }
lute = { source = "luau-lang/lute", version = "=0.1.0-nightly.20260218" }
rbx-aged-cli = { source = "roblox/rbx-aged-tool", version = "=5.8.1" }
rotrieve = { source = "Roblox/rotriever", version = "=0.5.26" }
